# string data1    # 执行状态
string data2    # 请求节点ID
string data3    # 请求命令
string data4    # 请求参数1
string data5    # 请求参数2
# string data6    # 请求类型(话题、服务、动作)    暂未用到
# string data7    # 暂未用到
---
string node_id      # 执行节点ID
string result_msg   # 请求结果信息
